<h2>Список актёров</h2>
<div class="input-group" id="search">
    <input type="text" class="form-control search" name="q" placeholder="Поиск">
    <div class="input-group-append">
        <button class="btn btn-info search-button" type="button">поиск</button>
    </div>
</div>
<div class="input-group">
    <div class="search-results"></div>
    <script type="text/template" id="search-item-template">
        <div class="search-item">
            <a href="/actors/<%= id %>"><%= name %></a>
        </div>
    </script>
</div>

<table class="table search-table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Имя</th>
    </tr>
    </thead>
    <tbody>
    {% for index,actor in actors %}
    <tr>
        <th scope="row">{{ actor.id }}</th>
        <td><a href="/actors/{{ actor.id }}">{{ actor.name|e }}</a></td>
    </tr>
    {% endfor  %}
    <script type="text/template" id="list-item-template">
        <tr>
            <th scope="row"><%= id %></th>
            <td><a href="/actors/<%= id %>"><%= name %></a></td>
        </tr>
    </script>
    </tbody>
</table>
